src/Entity/Car.php
<?php

namespace App\Entity;

use App\Repository\CarRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Nullable;
use PhpParser\Node\Expr\Cast\Double;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: CarRepository::class)]
#[Vich\Uploadable]

class Car
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?int $Mileage = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Power = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?int $Price = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE, nullable: true)]
    private ?\DateTimeImmutable $DateCirculation = null;

    // NOTE: This is not a mapped field of entity metadata, just a simple property.
    #[Vich\UploadableField(mapping: 'products', fileNameProperty: 'imageName')]
    private ?File $imageFile = null;

    #[ORM\Column(nullable: true)]
    private ?string $imageName = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;



    #[ORM\ManyToOne(inversedBy: 'cars')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Brand $brand = null;

    #[ORM\ManyToOne(inversedBy: 'cars')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Model $Model = null;

    #[ORM\ManyToOne(inversedBy: 'cars')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Color $Color = null;

    #[ORM\ManyToOne(inversedBy: 'cars')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Energy $energy = null;

    #[ORM\ManyToOne(inversedBy: 'cars')]
    private ?Year $Year = null;

    #[ORM\ManyToMany(targetEntity: Equipment::class, inversedBy: 'cars')]
    private Collection $Equipment;

    #[ORM\ManyToMany(targetEntity: Picture::class, inversedBy: 'cars')]
    private Collection $picture;

    public function __construct()
    {
        $this->Equipment = new ArrayCollection();
        $this->picture = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMileage(): ?int
    {
        return $this->Mileage;
    }

    public function setMileage(?int $Mileage): static
    {
        $this->Mileage = $Mileage;

        return $this;
    }

    public function getPower(): ?string
    {
        return $this->Power;
    }

    public function setPower(?string $Power): static
    {
        $this->Power = $Power;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->Price;
    }

    public function setPrice(?int $Price): static
    {
        $this->Price = $Price;

        return $this;
    }

    public function getDateCirculation(): ?\DateTimeImmutable
    {
        return $this->DateCirculation;
    }

    public function setDateCirculation(?\DateTimeImmutable $DateCirculation): static
    {
        $this->DateCirculation = $DateCirculation;

        return $this;
    }

    /**
     * @Groups({"car"})
     */
    public function getBrand(): ?Brand
    {
        return $this->brand;
    }

    public function setBrand(?Brand $brand): static
    {
        $this->brand = $brand;

        return $this;
    }


    /**
     * @Groups({"car"})
     */
    public function getModel(): ?Model
    {
        return $this->Model;
    }

    public function setModel(?Model $Model): static
    {
        $this->Model = $Model;

        return $this;
    }


    /**
     * @Groups({"car"})
     */
    public function getColor(): ?Color
    {
        return $this->Color;
    }

    public function setColor(?Color $Color): static
    {
        $this->Color = $Color;

        return $this;
    }


    /**
     * @Groups({"car"})
     */
    public function getEnergy(): ?Energy
    {
        return $this->energy;
    }

    public function setEnergy(?Energy $energy): static
    {
        $this->energy = $energy;

        return $this;
    }

    public function getYear(): ?Year
    {
        return $this->Year;
    }

    public function setYear(?Year $Year): static
    {
        $this->Year = $Year;

        return $this;
    }

    /**
     * @return Collection<int, Equipment>
     */
    public function getEquipment(): Collection
    {
        return $this->Equipment;
    }

    public function addEquipment(Equipment $equipment): static
    {
        if (!$this->Equipment->contains($equipment)) {
            $this->Equipment->add($equipment);
        }

        return $this;
    }

    public function removeEquipment(Equipment $equipment): static
    {
        $this->Equipment->removeElement($equipment);

        return $this;
    }

    /**
     * @return Collection<int, Picture>
     */
    public function getPicture(): Collection
    {
        return $this->picture;
    }

    public function addPicture(Picture $picture): static
    {
        if (!$this->picture->contains($picture)) {
            $this->picture->add($picture);
        }

        return $this;
    }

    public function removePicture(Picture $picture): static
    {
        $this->picture->removeElement($picture);

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;


        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text><text y=%221.3em%22 x=%220.2em%22 font-size=%2276%22 fill=%22%23fff%22>sf</text></svg>">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/themes/base/theme.css" integrity="sha512-Cq+AUPcDRLaoT5i4yI/o/4OgVgxv8uX8OpfT0Z+4n6Fkb0CP/u4c4EFLjUslmkmcfY4eitOlN1yY4Ai8JjSvmQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/themes/base/jquery-ui.min.css">     
        <link rel="stylesheet" href="{{asset('styles/styles.css') }}">
        <link rel="stylesheet" href="{{asset('styles/filter.css') }}">                    
        {% block stylesheets %}
        {% endblock %}
    </head>

    <body>
        {% block header %}
            {% include "_partials/_nav.html.twig" %}
            {% endblock %}
            <div class="content">
                {% block body %}{% endblock %}
            </div>
           
            {% block footer %}
            {% include '_partials/_footer.html.twig' with {'hours': hours} %}
            
            {% endblock %}


            {% block javascripts %}  
            <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/jquery-ui.js" integrity="sha512-ynDTbjF5rUHsWBjz7nsljrrSWqLTPJaORzSe5aGCFxOigRZRmwM05y+kuCtxaoCSzVGB1Ky3XeRZsDhbSLdzXQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
           <script src="https://cdn.jsdelivr.net/npm/axentix@0.5.3/dist/js/axentix.min.js"></script>
           <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>                                 
            {% endblock %}
            {% block script %}{% endblock %}
    </body>
</html>

templates/cgv.html.twig
{% extends "base.html.twig" %}

{% block title %}CGV
{% endblock %}

{% block body %}
<div class="container ms-5 py-3">
    <section>
        <h2>Informations générales</h2>
        <p>Nom de l'entreprise : Garage Parrot</p>
        <p>Adresse :32 rue des plantes</p>
        <p>Téléphone : 06.09.12.38.77</p>
        <p>Email : contact@parrot.fr</p>
    </section>

    <section>
        <h2>Responsable du contenu</h2>
        <p>Vincent Parrot, Directeur général</p>
        <p>Email : vincent@parrot.fr</p>
    </section>

    <section>
        <h2>Hébergeur du site</h2>
        <p>Ionos</p>
        <p>Adresse : 7 rue de la gare 57200 Sarreguemines</p>
        <p>Téléphone : 0970 808 911</p>
    </section>


    <section>
        <h3>Conditions d’utilisation</h3>
        <p>Ce site www.parrot.fr est proposé en différents langages web (HTML, HTML5, Javascript, CSS, etc…) pour un meilleur confort d’utilisation et un graphisme plus agréable.
        Nous vous recommandons de recourir à des navigateurs modernes comme Internet explorer, Safari, Firefox, Google Chrome, etc…
        Le garage Parrot met en œuvre tous les moyens dont elle dispose, pour assurer une information fiable et une mise à jour fiable de ses sites internet. Toutefois, des erreurs ou omissions peuvent survenir.
        L’internaute devra donc s’assurer de l’exactitude des informations auprès du garage Parrot et signaler toutes modifications du site qu’il jugerait utile. AntheDesign n’est en aucun cas responsable de l’utilisation faite de ces informations, et de tout préjudice direct ou indirect pouvant en découler.
        </p>

        <h3>Cookies</h3>
        <p>Le site www.parrot.fr peut-être amené à vous demander l’acceptation des cookies pour des besoins de statistiques et d’affichage. Un cookie est une information déposée sur votre disque dur par le serveur du site que vous visitez.
        Il contient plusieurs données qui sont stockées sur votre ordinateur dans un simple fichier texte auquel un serveur accède pour lire et enregistrer des informations. Certaines parties de ce site ne peuvent être fonctionnelles sans l’acceptation de cookies.
        </p>
        
        <h3>Liens hypertextes</h3>
        <p>Les sites internet peuvent offrir des liens vers d’autres sites internet ou d’autres ressources disponibles sur Internet. Le site ne dispose d’aucun moyen pour contrôler les sites en connexion avec ses sites internet.  
        Le site ne répond pas de la disponibilité de tels sites et sources externes, ni ne la garantit. Elle ne peut être tenue pour responsable de tout dommage, de quelque nature que ce soit, résultant du contenu de ces sites ou sources externes, et notamment des informations, produits ou services qu’ils proposent, ou de tout usage qui peut être fait de ces éléments.
        Les risques liés à cette utilisation incombent pleinement à l’internaute, qui doit se conformer à leurs conditions d’utilisation.
        </p>


        <h3>Services fournis</h3>
        L’ensemble des activités de la société ainsi que ses informations sont présentés sur notre site www.parrot.fr.
        Le site s’efforce de fournir des informations aussi précises que possible. Les renseignements figurant sur le site ne sont pas exhaustifs et les photos non contractuelles.
        
        Ils sont donnés sous réserve de modifications ayant été apportées depuis leur mise en ligne. Par ailleurs, tous les informations indiquées sur le site sont données à titre indicatif, et sont susceptibles de changer ou d’évoluer sans préavis.
        
        <h3>Limitation contractuelles sur les données</h3>
        Les informations contenues sur ce site sont aussi précises que possible et le site est mis à jour à différentes périodes de l’année, mais peut toutefois contenir des inexactitudes ou des omissions.
        Si vous constatez une lacune, erreur ou ce qui parait être un dysfonctionnement, merci de bien vouloir le signaler par courriel, à l’adresse contact@parrot.fr, en décrivant le problème de la manière la plus précise possible (page posant problème, type d’ordinateur et de navigateur utilisé…).
        Tout contenu téléchargé se fait aux risques et périls de l’utilisateur et sous sa seule responsabilité. En conséquence, ne saurait être tenu responsable d’un quelconque dommage subi par l’ordinateur de l’utilisateur ou d’une quelconque perte de données consécutives au téléchargement.
        De plus, l’utilisateur du site s’engage à accéder au site en utilisant un matériel récent, ne contenant pas de virus et avec un navigateur de dernière génération mis-à-jour.
        Les liens hypertextes mis en place dans le cadre du présent site internet en direction d’autres ressources présentes sur le réseau Internet ne sauraient engager la responsabilité de SARL ANTHEDESIGN.
        
        <h3>Propriété intellectuelle</h3>
        Tout le contenu du présent site, incluant, de façon non limitative, les graphismes, images, textes, vidéos, animations, sons, logos, gifs et icônes ainsi que leur mise en forme sont la propriété exclusive de la société à l’exception des marques, logos ou contenus appartenant à d’autres sociétés partenaires ou auteurs.
        Toute reproduction, distribution, modification, adaptation, retransmission ou publication, même partielle, de ces différents éléments est strictement interdite sans l’accord exprès par écrit de SARL ANTHEDESIGN. Cette représentation ou reproduction, par quelque procédé que ce soit, constitue une contrefaçon sanctionnée par les articles L.335-2 et suivants du Code de la propriété intellectuelle. Le non-respect de cette interdiction constitue une contrefaçon pouvant engager la responsabilité civile et pénale du contrefacteur. En outre, les propriétaires des Contenus copiés pourraient intenter une action en justice à votre encontre.
        
        <h3>Déclaration à la CNIL</h3>
        Conformément à la loi 78-17 du 6 janvier 1978 (modifiée par la loi 2004-801 du 6 août 2004 relative à la protection des personnes physiques à l’égard des traitements de données à caractère personnel) relative à l’informatique, aux fichiers et aux libertés, ce site a fait l’objet d’une déclaration 1656629 auprès de la Commission nationale de l’informatique et des libertés (www.cnil.fr).
        
        <h3>Litiges</h3>
        Les présentes conditions du site sont régies par les lois françaises et toute contestation ou litiges qui pourraient naître de l’interprétation ou de l’exécution de celles-ci seront de la compétence exclusive des tribunaux dont dépend le siège social de la société. La langue de référence, pour le règlement de contentieux éventuels, est le français.
        
        <h3>Données personnelles</h3>
        De manière générale, vous n’êtes pas tenu de nous communiquer vos données personnelles lorsque vous visitez notre site Internet www.parrot.fr.
        Cependant, ce principe comporte certaines exceptions.
        En effet, pour certains services proposés par notre site, vous pouvez être amenés à nous communiquer des données telles que : votre nom, votre fonction, le nom de votre société, votre adresse électronique, et votre numéro de téléphone. Tel est le cas lorsque vous remplissez le formulaire qui vous est proposé en ligne, dans la rubrique « contact ».
        Il est à noter que vous pouvez refuser de fournir vos données personnelles. Dans ce cas, vous ne pourrez pas utiliser les services du site, notamment celui de solliciter des renseignements sur notre société, ou de recevoir les lettres d’information.
        Enfin, nous pouvons collecter de manière automatique certaines informations vous concernant lors d’une simple navigation sur notre site internet, notamment des informations concernant l’utilisation de notre site, comme les zones que vous visitez et les services auxquels vous accédez, votre adresse IP, le type de votre navigateur, vos temps d’accès.  
        De telles informations sont utilisées exclusivement à des fins de statistiques internes, de manière à améliorer la qualité des services qui vous sont proposés.
        Les bases de données sont protégées par les dispositions de la loi du 1er juillet 1998 transposant la directive 96/9 du 11 mars 1996 relative à la protection juridique des bases de données.
    </section>
</div>
{% endblock %}

templates/filterajax.html.twig
{% for car in cars %}
<div class="col">
    <div class="card " id="car-{{car.id}}">
      {% if car.imageName %}
      <img src="{{vich_uploader_asset(car, 'imageFile') }}" alt="Image de la voiture" class="card-img-top" height="75%">
      {% else %}
      <img src="{{ asset('img/logo_vparrot.png') }}" alt="voiture par défaut" class="card-img-top" height="75%">
      {% endif %}
      <div class="card-body">
        <h5 class="card-title my-1">{{car.brand}} {{car.model}}</h5>
        <p class="card-text my-1">{{car.energy}}</p>
        <p class="card-text my-1">Année : {{car.year}}</p>
        <p class="card-text my-1">{{car.mileage}} km</p>
        <p class="card-text my-1">{{car.price}} €</p>
        <a href="{{ path('app_car_show', {'id': car.id}) }}" class="btn btn-danger d-flex justify-content-center">Détail</a>       
      </div>
    </div>
  </div>
{% endfor %}

templates/test.html copy.twig
{% extends "base.html.twig" %}

{% block title %}Parrot
{% endblock %}

{% block stylesheets %}      

{% endblock %}

{% block body %}


<h1 class="text-center">Filtrage des annonces de voitures par prix</h1>
    <!-- Champs d'entrée pour spécifier le prix minimum et maximum -->
    <div class="text-center">
    <label for="minPriceInput">Prix minimum:</label>
    <input type="number" id="minPriceInput" name="minPriceInput">
    
    <label for="maxPriceInput">Prix maximum:</label>
    <input type="number" id="maxPriceInput" name="maxPriceInput">
    
    <!-- Bouton de filtrage -->
    <button id="filterButton">Filtrer</button>
    <!-- END  -->

    <!-- SLIDER  de filtrage V2 -->
    <div class="mt-5">
        <h3>Filtre V2</h3>
        <div>
            <label for="priceRange">Filtrer par prix :</label>
        </div>
        <div>
            <input type="range" id="priceRange" min="0" max="100000" step="1000">
        </div>
        <div>
            <span id="minPrice">0</span> - <span id="maxPrice">100000</span> euros
        </div>
    </div>
    </div>
    <!-- END  -->


     <!-- SLIDER de filtrage V3 -->
     <div class="container ms-5 mb-5">
        <h3>Filtre V3</h3>
            
        <div class="row">
            <!-- Filter price -->
            <div class="col">
                <div class="ms-5">
                    <label for="amount">Prix:</label>
                    <input type="text" id="amount" readonly style="border:0; color:#f6931f; font-weight:bold; " > 
                </div>
                <div id="slider-range" class="ms-5 mb-5"  style="width:200px">
                </div>
            </div> 


            <!-- Filter mileage -->
            <div class="col">
                <div class="ms-5">
                    <label for="amount">Prix:</label>
                    <input type="text" id="amount-mileage" readonly style="border:0; color:#f6931f; font-weight:bold; " > 
                </div>
                <div id="slider-range-mileage" class="ms-5 mb-5"  style="width:200px">
                </div>
            </div>
        </div>     
    </div>


    <!-- END  -->
        


    <!-- Zone pour afficher les résultats d'origine -->
    <div id="filteredResults" style="background-color: rgb(115, 115, 115)" height: "100px";  >
        <div id="ListCar d-flex justify-content-center">
            <p class="ms-5">Résultats d'origine = Liste de toutes les voitures</p>
            {% for car in cars %}
            <div class="border border-primary m-5 text-center" style="width: 200px;">
                <p>{{ car.brand }} {{ car.model }} - {{ car.price }} euros</p> 
            </div>
            {% endfor %}
        </div>
    </div>




{% endblock %}

templates/test.html.twig
{% extends "base.html.twig" %}

{% block title %}Parrot
{% endblock %}

{% block stylesheets %}      

{% endblock %}

{% block body %}


<h1 class="text-center">Filtrage des annonces de voitures</h1>
 

     <!-- SLIDER de filtrage V3 -->
     <div class="container ms-5 mb-5">
        <h3>Filtre V3</h3>
            
        <div class="row">
            <!-- Filter price -->
            <div class="col-lg-4">
                <div class="ms-5">
                    <label for="amount">Prix:</label>
                    <input type="text" id="amount" readonly style="border:0; color:#f6931f; font-weight:bold; " > 
                </div>
                <div id="slider-range" class="ms-5 mb-5"  style="width:200px">
                </div>
            </div> 


            <!-- Filter mileage -->
            <div class="col-lg-4">
                <div class="ms-5">
                    <label for="mileage">Kilomètre:</label>
                    <input type="text" id="mileage" readonly style="border:0; color:#f6931f; font-weight:bold; " > 
                </div>
                <div id="slider-range-mileage" class="ms-5 mb-5"  style="width:200px">
                </div>
            </div>
        </div>     
    </div>


    <!-- END  -->
        


    <!-- Zone pour afficher les résultats d'origine -->
    <div id="filteredResults" style="background-color: rgb(115, 115, 115)" height: "100px";  >
        <div id="ListCar d-flex justify-content-center">
            <p class="ms-5">Résultats d'origine = Liste de toutes les voitures</p>
            {% for car in cars %}
            <div class="border border-primary m-5 text-center" style="width: 200px;">
                <p>{{ car.brand }} {{ car.model }} - {{ car.mileage }} km - {{ car.price }} €</p> 
            </div>
            {% endfor %}
        </div>
    </div>




{% endblock %}